FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
# Создаём папку momo-store и копируем туда все файлы из корня
RUN cd /usr/share/nginx/html && \
    mkdir -p momo-store && \
    find . -maxdepth 1 -not -name momo-store -not -name '.' -exec cp -r {} momo-store/ \;
# Копируем корневой nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
