server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        proxy_set_header Cookie "";
        proxy_set_header X-CSRFToken "";
        proxy_set_header X-CSRF-TOKEN "";
    }

    location /momo-store/ {
        rewrite ^/momo-store/(.*) /$1 break;
        try_files $uri /index.html;
    }

    location / {
        try_files $uri /index.html;
    }
}
